### ISSUE TITLE
website on iPhone Xs

### ISSUE THREAD

**Issue by ghost** [udu3324/PNGskin#1]
it look like not good

![image](https://user-images.githubusercontent.com/109896209/186416244-341f0736-1eca-4679-8350-581a166431f0.png)

**Comment by udu3324** [comment]
I'm not sure why that happens. Will fix later.

**Comment by ghost** [comment]
fix it now 🤬🤬🤬

**Comment by udu3324** [comment]
> fix it now 🤬🤬🤬

This issue (i think) has been fixed in https://github.com/udu3324/PNGskin/commit/77059c21111651fce2a845c9c5a7f2831663ba78.
